localStorage.clear()
const employees = [
  {
    Id: 1,
    firstName: "Ahmed",
    email: "employee1@example.com",
    password: "123",
    taskCount: {         // Separate object for task counts
      newTask: 2,
      active: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        taskNumber: 1,
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Design Homepage",
        taskDescription: "Create a responsive homepage design for the website.",
        taskDate: "2023-10-15",
        category: "Design",
      },
      {
        taskNumber: 2,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix Login Bug",
        taskDescription: "Resolve the issue with the login functionality.",
        taskDate: "2023-10-10",
        category: "Development",
      },
      {
        taskNumber: 3,
        active: true,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Write API Documentation",
        taskDescription: "Document the new API endpoints for developers.",
        taskDate: "2023-10-20",
        category: "Documentation",
      },
    ],
  },
  {
    Id: 2,
    firstName: "Fatima",
    email: "employee2@example.com",
    password: "123",
    taskCount: {         // Separate object for task counts
      newTask: 1,
      active: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskNumber: 1,
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Optimize Database",
        taskDescription: "Improve database query performance.",
        taskDate: "2023-10-18",
        category: "Development",
      },
      {
        taskNumber: 2,
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create User Dashboard",
        taskDescription: "Develop a user-friendly dashboard for clients.",
        taskDate: "2023-10-22",
        category: "Development",
      },
      {
        taskNumber: 3,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Test Payment Gateway",
        taskDescription: "Ensure the payment gateway integration works flawlessly.",
        taskDate: "2023-10-12",
        category: "Testing",
      },
    ],
  },
  {
    Id: 3,
    firstName: "Ali",
    email: "employee3@example.com",
    password: "123",
    taskCount: {         // Separate object for task counts
      newTask: 1,
      active: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskNumber: 1,
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Plan Marketing Campaign",
        taskDescription: "Outline the strategy for the upcoming marketing campaign.",
        taskDate: "2023-10-25",
        category: "Marketing",
      },
      {
        taskNumber: 2,
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Update Social Media",
        taskDescription: "Post new content on all social media platforms.",
        taskDate: "2023-10-17",
        category: "Marketing",
      },
      {
        taskNumber: 3,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Analyze Competitors",
        taskDescription: "Research and analyze competitor strategies.",
        taskDate: "2023-10-08",
        category: "Research",
      },
    ],
  },
  {
    Id: 4,
    firstName: "Aisha",
    email: "employee4@example.com",
    password: "123",
    taskCount: {         // Separate object for task counts
      newTask: 1,
      active: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskNumber: 1,
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Develop Mobile App",
        taskDescription: "Start development on the new mobile application.",
        taskDate: "2023-10-30",
        category: "Development",
      },
      {
        taskNumber: 2,
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Write Test Cases",
        taskDescription: "Create test cases for the mobile app.",
        taskDate: "2023-10-19",
        category: "Testing",
      },
      {
        taskNumber: 3,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix UI Bugs",
        taskDescription: "Resolve UI issues reported by the QA team.",
        taskDate: "2023-10-14",
        category: "Development",
      },
    ],
  },
  {
    Id: 5,
    firstName: "Omar",
    email: "employee5@example.com",
    password: "123",
    taskCount: {         // Separate object for task counts
      newTask: 1,
      active: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskNumber: 1,
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Prepare Financial Report",
        taskDescription: "Compile and analyze financial data for the quarterly report.",
        taskDate: "2023-10-28",
        category: "Finance",
      },
      {
        taskNumber: 2,
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Audit Expenses",
        taskDescription: "Review and verify company expenses for accuracy.",
        taskDate: "2023-10-21",
        category: "Finance",
      },
      {
        taskNumber: 3,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Update Budget",
        taskDescription: "Adjust the budget based on recent financial data.",
        taskDate: "2023-10-09",
        category: "Finance",
      },
    ],
  },
];

const admin = [
  {
    Id: 101,
    firstName: "Khalid",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employee = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return({employee, admin})

};
